In [17]:
import numpy as np
# Proyecto: Crecimiento Poblacional
# Autores: Mia de la Cruz, Fatima Vazquez, Juan Castro
print('Proyecto: Crecimiento Poblacional \nAutores: Mia de la Cruz, Fatima Vazquez, Juan Castro\Este codigo sireve para calcular una proyeccion a 100 años en plazos de 20, utilizando 5 grupos\nde edad los cuales se separan entre 0-19, 20-39, 40-59, 60-79, 80-99, a continuacion se calculo la cantidad de poblacion general y poblacion femenina,\nposteriromente la fecundidad, despues el indice de supervivencia. Una vez que ya contamos con todos esos datos se implementaron en una matriz de Leslie\npara proyectar los resultados que por último se graficaron. ')


Proyecto: Crecimiento Poblacional 
Autores: Mia de la Cruz, Fatima Vazquez, Juan Castro\Este codigo sireve para calcular una proyeccion a 100 años en plazos de 20, utilizando 5 grupos
de edad los cuales se separan entre 0-19, 20-39, 40-59, 60-79, 80-99, a continuacion se calculo la cantidad de poblacion general y poblacion femenina,
posteriromente la fecundidad, despues el indice de supervivencia. Una vez que ya contamos con todos esos datos se implementaron en una matriz de Leslie
para proyectar los resultados que por último se graficaron. 


In [18]:

import pandas as pd #instale la libreria pandas
#Definir poblacion (Vector M)
#instalar pandas openpyxl xlrd
#Cargar archivos
Ptxls = pd.read_excel("PoblacionTotalMex2020.xls")#[1]
Pt2020=(Ptxls.iloc[18,1])
print("Poblacion total:", Pt2020)
Pse = pd.read_excel("Poblacionporsexoyedad.xls")#[2]

#Definir primer grupo de poblacion (M1)
C1 = Pse.iloc[4, 1:9].sum()
N1 = C1*Pt2020//100
print("\nPorcentaje de personas de 0 a 19:",C1)
print("Cantidad de personas de 0 a 19:", N1)
M1P = Pse.iloc[4, 1:8:2].sum()
M1C = M1P*Pt2020//100
print("Porcentaje de mujeres de 0 a 19:", M1P)
print("Cantidad de mujeres de 0 a 19:", M1C)

#Definir segundo grupo de poblacion (M2)
C2 = Pse.iloc[4, 9:17].sum()
N2 = C2*Pt2020//100
print("\nPorcentaje de personas de 20 a 39:", C2)
print("Cantidad de personas de 20 a 39:", N2)
M2P = Pse.iloc[4, 9:16:2].sum()
M2C = M2P*Pt2020//100
print("Porcentaje de mujeres de 20 a 39: ", M2P)
print("Cantidad de mujeres de 20 a 39: ", M2C)

#Definir tercer grupo de poblacion (M3)
C3 = Pse.iloc[4, 17:25].sum()
N3 = C3*Pt2020//100
print("\nPorcentaje de personas igual o mayor de 40 a 59:", C3)
print("Cantidad de personas igual o mayor de 40 a 59:", N3)
M3P = Pse.iloc[4, 17:24:2].sum()
M3C = M3P*Pt2020//100
print("Porcentaje de mujeres de 40 a 59: ", M3P)
print("Cantidad de mujeres de 40 a 59: ", M3C)

#Definir tercer grupo de poblacion (M4)
C4 = Pse.iloc[4, 25:33].sum()
N4 = C3*Pt2020//100
print("\nPorcentaje de personas igual o mayor de 60 a 79:", C4)
print("Cantidad de personas igual o mayor de 60 a 79:", N4)
M4P = Pse.iloc[4, 25:32:2].sum()
M4C = M4P*Pt2020//100
print("Porcentaje de mujeres de 60 a 79: ", M4P)
print("Cantidad de mujeres de 60 a 79: ", M4C)

#Definir tercer grupo de poblacion (M5)
C5 = Pse.iloc[4, 33:41].sum()
N5 = C5*Pt2020//100
print("\nPorcentaje de personas igual o mayor de 80 a 99:", C5)
print("Cantidad de personas igual o mayor de 80 a 99:", N5)
M5P = Pse.iloc[4, 33:40:2].sum()
M5C = M5P*Pt2020//100
print("Porcentaje de mujeres de 80 a 99: ", M5P)
print("Cantidad de mujeres de 80 a 99: ", M5C)

print("\nPorcentaje original:", Pse.iloc[4, 1:38].sum())
print("Porcentaje usando las variables generadas:", C1+C2+C3+C4+C5)

Poblacion total: 126014024

Porcentaje de personas de 0 a 19: 33.849020234799994
Cantidad de personas de 0 a 19: 42654512.0
Porcentaje de mujeres de 0 a 19: 16.7129667339
Cantidad de mujeres de 0 a 19: 21060681.0

Porcentaje de personas de 20 a 39: 30.9018624512
Cantidad de personas de 20 a 39: 38940680.0
Porcentaje de mujeres de 20 a 39:  15.8816237278
Cantidad de mujeres de 20 a 39:  20013073.0

Porcentaje de personas igual o mayor de 40 a 59: 23.2060926874
Cantidad de personas igual o mayor de 40 a 59: 29242931.0
Porcentaje de mujeres de 40 a 59:  12.151761151499999
Cantidad de mujeres de 40 a 59:  15312923.0

Porcentaje de personas igual o mayor de 60 a 79: 10.281529667500001
Cantidad de personas igual o mayor de 60 a 79: 29242931.0
Porcentaje de mujeres de 60 a 79:  5.4731382865
Cantidad de mujeres de 60 a 79:  6896921.0

Porcentaje de personas igual o mayor de 80 a 99: 1.7614949592000002
Cantidad de personas igual o mayor de 80 a 99: 2219730.0
Porcentaje de mujeres de 80 a 99:  0

In [19]:
#Definir fecundidades
#Cargar el archivo
Nat = pd.read_csv("Natalidad.csv", engine= "python", encoding = "latin-1", sep = ",")#[3]
#Corregir el archivo
for col in Nat.columns: 
    Nat[col] = Nat[col].astype(str).str.strip()
    Nat[col] = Nat[col].str.replace(",", "", regex=False)
    Nat[col] = pd.to_numeric(Nat[col], errors="coerce")
    
#Definir la fertilidad en el grupo 1
Na1 = Nat.loc[2:6, "2020"].sum()
F1 = Na1*0.5*20/M1C
print("\nHijas de mujeres de 0 a 19: ", Na1)
print("Fecundidad en mujeres de 0 a 19: ", F1)

#Definir la fecundidad en el grupo 2
Na2 = Nat.loc[7:13, "2020"].sum()
F2 = Na2*0.5*20/M2C
print("\nHijas de mujeres de 20 a 39: ", Na2)
print("Fecundidad en mujeres de 20 a 39: ", F2)

#Definir la fecundidad en el grupo 3
Na3 = Nat.loc[14:21, "2020"].sum()
F3 = Na3*0.5*20/M3C
print("\nHijas de mujeres de 40 a 59: ", Na3)
print("Fecundidad en mujeres de 40 a 59: ", F3)

#No hay nacimientos regristrados de 60 en adelante, por lo que su fecundidad es de 0
Na4 = 0
F4 = Na4*0.5*20/M4C
print("\nHijas de mujeres de 60 a 79: ", Na4)
print("Fecundidad en mujeres de 60 a 79: ", F4)

#Mismo caso que el anterior
Na5 = 0
F5 = Na5*0.5*20/M5C
print("\nHijas de mujeres de 80 a 99: ", Na5)
print("Fecundidad en mujeres de 80 a 99: ", F5)


Hijas de mujeres de 0 a 19:  236440.0
Fecundidad en mujeres de 0 a 19:  0.11226607534675635

Hijas de mujeres de 20 a 39:  1290449.0
Fecundidad en mujeres de 20 a 39:  0.6448030245030336

Hijas de mujeres de 40 a 59:  102322.0
Fecundidad en mujeres de 40 a 59:  0.06682068472492156

Hijas de mujeres de 60 a 79:  0
Fecundidad en mujeres de 60 a 79:  0.0

Hijas de mujeres de 80 a 99:  0
Fecundidad en mujeres de 80 a 99:  0.0


In [20]:
#Definir el indice de supervivencia
#Cargar archivo 2019
d2019 = pd.read_excel("Defunciones 2019.xls")
#Limpiarlo
for col in d2019.columns:
    if d2019[col].dtype == "object":
        d2019[col] = d2019[col].astype(str).str.replace(",", "").str.strip()
        d2019[col] = pd.to_numeric(d2019[col], errors="coerce")
#Decesos del grupo 1 en 2019
dM119 = d2019.iloc[6:11, 3].sum()
#Decesos del grupo 2 en 2019
dM219 = d2019.iloc[11:15, 3].sum()
#Decesos del grupo 3 en 2019
dM319 = d2019.iloc[15:19, 3].sum()
#Decesos del grupo 4 en 2019
dM419 = d2019.iloc[19:23, 3].sum()

#Cargar archivo 2018
d2018 = pd.read_excel("Defunciones2018.xls")
#Limpiarlo
for col in d2018.columns:
    if d2018[col].dtype == "object":
        d2018[col] = d2018[col].astype(str).str.replace(",", "").str.strip()
        d2018[col] = pd.to_numeric(d2018[col], errors="coerce")
#Decesos del grupo 1 en 2018
dM118 = d2018.iloc[6:11, 3].sum()
#Decesos del grupo 2 en 2018
dM218 = d2018.iloc[11:15, 3].sum()
#Decesos del grupo 3 en 2018
dM318 = d2018.iloc[15:19, 3].sum()
#Decesos del grupo 4 en 2018
dM418 = d2018.iloc[19:23, 3].sum()

#Cargar archivo 2017
d2017 = pd.read_excel("Defunciones2017.xls")
#Limpiarlo
for col in d2017.columns:
    if d2017[col].dtype == "object":
        d2017[col] = d2017[col].astype(str).str.replace(",", "").str.strip()
        d2017[col] = pd.to_numeric(d2017[col], errors="coerce")
#Decesos del grupo 1 en 2017
dM117 = d2017.iloc[6:11, 3].sum()
#Decesos del grupo 2 en 2019
dM217 = d2017.iloc[11:15, 3].sum()
#Decesos del grupo 3 en 2019
dM317 = d2017.iloc[15:19, 3].sum()
#Decesos del grupo 4 en 2019
dM417 = d2017.iloc[19:23, 3].sum()

#Promediar los decesos
dp1 = (dM117 + dM118 + dM119 )//3
dp2 = (dM217 + dM218 + dM219 )//3
dp3 = (dM317 + dM318 + dM319 )//3
dp4 = (dM417 + dM418 + dM419 )//3
#Calcular indice de mortalidad
q1 = dp1/M1C
q2 = dp2/M2C
q3 = dp3/M3C
q4 = dp4/M4C
#Calcular indice de supervivencia
P1 = 1 - q1
P2 = 1 - q2
P3 = 1 - q3
P4 = 1 - q4
print ("\nProbabilidad de que el grupo 1 llegue hasta el grupo 2: ", P1)
print ("Probabilidad de que el grupo 2 llegue hasta el grupo 3: ", P2)
print ("Probabilidad de que el grupo 3 llegue hasta el grupo 4: ", P3)
print ("Probabilidad de que el grupo 4 llegue hasta el grupo 5: ", P4)


Probabilidad de que el grupo 1 llegue hasta el grupo 2:  0.9991587166625808
Probabilidad de que el grupo 2 llegue hasta el grupo 3:  0.9991704922077684
Probabilidad de que el grupo 3 llegue hasta el grupo 4:  0.996562576589721
Probabilidad de que el grupo 4 llegue hasta el grupo 5:  0.9831735059746226


In [21]:
import numpy as np
#Creamos la matriz de leslie (lm) y el Vector de poblacion (Vp)
Lm = np.array([[F1, F2, F3, F4, F5],[P1, 0, 0, 0, 0],[0, P2, 0, 0, 0],[0, 0, P3, 0, 0], [0, 0, 0, P4, 0]])
print("Matriz de lesley:\n",Lm)
Vp1 = np.array([[M1C],[M2C],[M3C],[M4C],[M5C]])
print("\nVector poblacion:\n", 2*Vp1 )
Vp2 = Lm.dot(Vp1)
print("\n\nNueva poblacion 20 años despues:\n", 2*Vp2)
Vp3 = Lm.dot(Vp2)
print("\nNueva poblacion 40 años despues:\n", 2*Vp3)
Vp4 = Lm.dot(Vp3)
print("\nNueva poblacion 60 años despues:\n", 2*Vp4)
Vp5 = Lm.dot(Vp4)
print("\nNueva poblacion 80 años despues:\n", 2*Vp5)
Vp6 = Lm.dot(Vp5)
print("\nNueva poblacion 100 años despues:\n", 2*Vp6)

Matriz de lesley:
 [[0.11226608 0.64480302 0.06682068 0.         0.        ]
 [0.99915872 0.         0.         0.         0.        ]
 [0.         0.99917049 0.         0.         0.        ]
 [0.         0.         0.99656258 0.         0.        ]
 [0.         0.         0.         0.98317351 0.        ]]

Vector poblacion:
 [[42121362.]
 [40026146.]
 [30625846.]
 [13793842.]
 [ 2519736.]]


Nueva poblacion 20 años despues:
 [[32584220.]
 [42085926.]
 [39992944.]
 [30520572.]
 [13561740.]]

Nueva poblacion 40 años despues:
 [[33467590.77369159]
 [32556807.4386512 ]
 [42051015.39643972]
 [39855471.31804843]
 [30007017.7775909 ]]

Nueva poblacion 60 años despues:
 [[27559880.61424715]
 [33439435.04723012]
 [32529801.31319066]
 [41906468.25168999]
 [39184843.46803668]]

Nueva poblacion 80 años despues:
 [[26829552.08742646]
 [27536694.94590512]
 [33411696.77529062]
 [32417982.61262497]
 [41201329.31402826]]

Nueva poblacion 100 años despues:
 [[23000385.15845014]
 [26806980.83230489]
 

In [22]:
from pydataset import data
from bokeh.plotting import figure
from bokeh.io import output_file, show
from bokeh.layouts import column
data = np.column_stack([Vp1*2, Vp2*2, Vp3*2, Vp4*2, Vp5*2, Vp6*2])

años = [0, 20, 40, 60, 80, 100]
edad = ["0-19","20-39","40-59","60-79","80-99"]
plots = []

for i in range(5): # por los 5 grupos de edad
    p = figure(
        title=f"Grupo de edad: {edad[0+i]}",
        x_axis_label="Años",
        y_axis_label="Población",
        y_axis_type="linear"
    )
    p.line(años, data[i], line_width=3)
    p.yaxis.formatter.use_scientific = False
    plots.append(p)

# Mostrar todos apilados
show(column(*plots))

In [23]:
print("[1] Instituto Nacional de Estadística y Geografía (INEGI), "
    "“Población total,” en *Estructura de la población*. "
    "Disponible en: https://www.inegi.org.mx/temas/estructura"
    "[Accedido: 21-sep-2025, 20:58:54].\n\n"
    
    "[2] Instituto Nacional de Estadística y Geografía (INEGI),"
    "“Población por edad y sexo,” en *Estructura de la población*."
    "Disponible en: https://www.inegi.org.mx/temas/estructura"
    "[Accedido: 21-sep-2025, 03:35:32].\n\n"

    "[3] Instituto Nacional de Estadística y Geografía (INEGI),"
    "“Nacimientos registrados por edad de la madre al nacimiento, según año de registro.”"
    "Disponible en: https://www.inegi.org.mx/sistemas/olap/consulta/general_ver4/MDXQueryDatos.asp?proy="
    "[Accedido: 21-sep-2025].")

[1] Instituto Nacional de Estadística y Geografía (INEGI), “Población total,” en *Estructura de la población*. Disponible en: https://www.inegi.org.mx/temas/estructura[Accedido: 21-sep-2025, 20:58:54].

[2] Instituto Nacional de Estadística y Geografía (INEGI),“Población por edad y sexo,” en *Estructura de la población*.Disponible en: https://www.inegi.org.mx/temas/estructura[Accedido: 21-sep-2025, 03:35:32].

[3] Instituto Nacional de Estadística y Geografía (INEGI),“Nacimientos registrados por edad de la madre al nacimiento, según año de registro.”Disponible en: https://www.inegi.org.mx/sistemas/olap/consulta/general_ver4/MDXQueryDatos.asp?proy=[Accedido: 21-sep-2025].
